# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'EasyPOS' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

  # Pods for EasyPOS
  pod 'Firebase/Core', '~> 6.3.0'
  # pod 'Firebase/Analytics'
  pod 'Firebase/Messaging', '~> 6.3.0'

  target 'EasyPOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'EasyPOS-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EasyPOS-tvOS

  target 'EasyPOS-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
